// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerCoachApplication.Data.Context;

#nullable disable

namespace PlayerCoachApplication.Data.Migrations
{
    [DbContext(typeof(PlayerApplicationDBContext))]
    [Migration("20250909225528_AddSportToCoachApplicationViewModel")]
    partial class AddSportToCoachApplicationViewModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerCoachApplication.Data.Models.CoachApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSportName")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoachApplicationModel");
                });

            modelBuilder.Entity("PlayerCoachApplication.Data.Models.PlayerApplicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSportName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerApplicationModel");
                });

            modelBuilder.Entity("PlayerCoachApplication.Data.Models.SelectedPositionToSportModel", b =>
                {
                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sport")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Position", "Sport");

                    b.ToTable("SelectedPositionToSport");
                });
#pragma warning restore 612, 618
        }
    }
}
