// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerCoachApplication.Data.Context;

#nullable disable

namespace PlayerCoachApplication.Data.Migrations
{
    [DbContext(typeof(PlayerApplicationDBContext))]
    [Migration("20250529225719_Sport")]
    partial class Sport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerCoachApplication.Data.Models.SelectedPositionToSportModel", b =>
                {
                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sport")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Position", "Sport");

                    b.ToTable("SelectedPositionToSport");
                });
#pragma warning restore 612, 618
        }
    }
}
